name: goob_by_me
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  google_maps_flutter: ^2.0.3
  intl: ^0.17.0
  json_annotation: ^4.0.1
  logging: ^1.0.1
  pedantic: ^1.11.0
  shared_preferences: ^2.0.5
  uuid: ^3.0.4
  # device_preview: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  json_serializable: ^4.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/duotone/
    - assets/icons/light/
    - assets/icons/regular/
    - assets/icons/solid/
    - assets/images/ads/
    - assets/images/
    - assets/styles/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
